.Dd Mar 7, 2021
.Dt VR0 1
.Os
.Th VR0 1
.Sh NAME
r0v \- visual radare zero
.Sh SYNOPSIS
.Nm r0v
.Ar file
.Sh DESCRIPTION
Visual mode for r0(1)
.Pp
.Sh KEYS
.Bl -tag -width Fl
.It hjkl
seek left(-1), down(+16), up(-16), right(+1)
.It +-*/
change block size (+1,-1,+16,-16)
.It :[cmd]
input r0 command
.It b
prompt to change block size
.It s
prompt seek address
.It r
prompt for resize, remove command
.It p
change print mode
.It :
enter raw r0 command
.It ?
show help
.It q
quit program
.Pp
.Sh SEE ALSO
.Pp
.Xr r0(1)
.Sh AUTHORS
.PP
pancake <@nopcode.org>
